https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

# PyTorch 基础 : 张量
在第一章中我们已经通过官方的入门教程对PyTorch有了一定的了解，这一章会详细介绍PyTorch 里面的基础知识。
全部掌握了这些基础知识，在后面的应用中才能更加快速进阶，如果你已经对PyTorch有一定的了解，可以跳过此章

In [1]:
# 首先要引入相关的包
import torch
import numpy as np
#打印一下版本
torch.__version__

'2.1.2+cu121'

## 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。
与ndarray的最大区别就是，PyTorch的Tensor可以在 GPU 上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。

下面我们生成一个简单的张量

In [2]:
x = torch.rand(2, 3)
x

tensor([[0.3897, 0.5593, 0.4393],
        [0.6506, 0.7591, 0.7304]])

以上生成了一个，2行3列的的矩阵，我们看一下他的大小：

In [5]:
# 可以使用与numpy相同的shape属性查看
print(x.shape)
# 也可以使用size()函数，返回的结果都是相同的
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，其坐标是|n|维空间内，有|n|个分量的一种量， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。 (来自百度百科)

下面我们来生成一些多维的张量：

In [6]:
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.2589, 0.6411, 0.6829, 0.5636, 0.3748],
          [0.0068, 0.5990, 0.9061, 0.0436, 0.6267],
          [0.0583, 0.3076, 0.7439, 0.7521, 0.6416],
          [0.7970, 0.7927, 0.3973, 0.7449, 0.8266]],

         [[0.5190, 0.7649, 0.7978, 0.0191, 0.9661],
          [0.2939, 0.2917, 0.9423, 0.1018, 0.4544],
          [0.6114, 0.0585, 0.6358, 0.9425, 0.2570],
          [0.7764, 0.9968, 0.8676, 0.9816, 0.6632]],

         [[0.5290, 0.3435, 0.6624, 0.1365, 0.6548],
          [0.3173, 0.8724, 0.0179, 0.9457, 0.4813],
          [0.7894, 0.9145, 0.6725, 0.6895, 0.0629],
          [0.4937, 0.6669, 0.9741, 0.7798, 0.7864]]],


        [[[0.8458, 0.1517, 0.4444, 0.2176, 0.2235],
          [0.2263, 0.6407, 0.6272, 0.1418, 0.2562],
          [0.0634, 0.1410, 0.6249, 0.9655, 0.8958],
          [0.7947, 0.0484, 0.9669, 0.0743, 0.6938]],

         [[0.4585, 0.3338, 0.9413, 0.6567, 0.2347],
          [0.2672, 0.9551, 0.3947, 0.5793, 0.0660],
          [0.1709, 0.0684, 0.8112, 0.9951, 0.5614],
  

在同构的意义下，第零阶张量 （r = 0） 为标量 （Scalar），第一阶张量 （r = 1） 为向量 （Vector）， 第二阶张量 （r = 2） 则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：


In [7]:
#我们直接使用现有数字生成
scalar =torch.tensor(3.1433223)
print(scalar)
#打印标量的大小
scalar.size()

tensor(3.1433)


torch.Size([])

对于标量，我们可以直接使用 .item() 从中取出其对应的python对象的数值

In [8]:
scalar.item()

3.143322229385376

特别的：如果张量中只有一个元素的tensor也可以调用`tensor.item`方法

In [9]:
tensor = torch.tensor([3.1433223]) 
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [10]:
tensor.item()

3.143322229385376

### 基本类型
Tensor的基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有
byte和chart型

In [11]:
long=tensor.long()
long

tensor([3])

In [12]:
half=tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [14]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [15]:
flo = tensor.float()
flo

tensor([3.1433])

In [16]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [17]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [18]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

### Numpy转换
使用numpy方法将Tensor转为ndarray

In [20]:
a = torch.randn((3, 2))
# tensor转化为numpy
numpy_a = a.numpy()
print(numpy_a)

[[-0.47585154  0.33732265]
 [ 0.38890845  0.15524532]
 [ 1.2715795  -0.5423139 ]]


numpy转化为Tensor


In [21]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[-0.4759,  0.3373],
        [ 0.3889,  0.1552],
        [ 1.2716, -0.5423]])

***Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。***

### 设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [22]:
cpu_a=torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [23]:
gpu_a=cpu_a.cuda()
gpu_a.type()

'torch.cuda.FloatTensor'

使用.cpu方法将tensor移动到cpu

In [24]:
cpu_b=gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

如果我们有多GPU的情况，可以使用to方法来确定使用那个设备，这里只做个简单的实例：

In [25]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#将tensor传送到设备
gpu_b=cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

### 初始化
Pytorch中有许多默认的初始化方法可以使用

In [26]:
# 使用[0,1]均匀分布随机初始化二维数组
rnd = torch.rand(5, 3)
rnd

tensor([[0.2359, 0.5203, 0.7251],
        [0.4915, 0.1640, 0.2172],
        [0.8341, 0.2372, 0.4915],
        [0.1921, 0.7209, 0.5992],
        [0.1284, 0.3840, 0.7777]])

In [27]:
##初始化，使用1填充
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [28]:
##初始化，使用0填充
zero=torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [29]:
#初始化一个单位矩阵，即对角线为1 其他为0
eye=torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

### 常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么他们二者基本是一致的：

In [30]:
x = torch.randn(3, 3)
print(x)

tensor([[ 0.4040, -0.5876,  0.9833],
        [-0.4204, -0.1848,  0.7383],
        [-0.1001, -0.1034,  2.9289]])


In [31]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([0.9833, 0.7383, 2.9289]) tensor([2, 2, 2])


In [32]:
# 每行 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([0.7998, 0.1331, 2.7254])


In [33]:
y=torch.randn(3, 3)
z = x + y
print(z)

tensor([[ 1.0290, -1.4024,  0.8801],
        [-1.1592,  1.3096,  0.5408],
        [-1.3058,  0.2948,  2.7238]])


正如官方60分钟教程中所说，以_为结尾的，均会改变调用值

In [34]:
# add 完成后x的值改变了
x.add_(y)
print(x)

tensor([[ 1.0290, -1.4024,  0.8801],
        [-1.1592,  1.3096,  0.5408],
        [-1.3058,  0.2948,  2.7238]])


张量的基本操作都介绍的的差不多了，下一章介绍PyTorch的自动求导机制