# numpy中reshape函数的三种常见相关用法

numpy.arange(n).reshape(a, b)    依次生成n个自然数，并且以a行b列的数组形式显示

In [2]:
import numpy as np
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [1]:
import numpy as np
np.arange(16).reshape(2,8) #生成16个自然数，以2行8列的形式显示

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

mat (or array).reshape(c, -1)     必须是矩阵格式或者数组格式，才能使用 .reshape(c, -1) 函数， 表示将此矩阵或者数组重组，以 c行d列的形式表示

arr.shape # (a,b)
 
arr.reshape(m,-1) #改变维度为m行、d列 （-1表示列数自动计算，d= a*b /m ）
 
arr.reshape(-1,m) #改变维度为d行、m列 （-1表示行数自动计算，d= a*b /m ）

-1的作用就在此: 自动计算d：d=数组或者矩阵里面所有的元素个数/c, d必须是整数，不然报错）

（reshape(-1, m)即列数固定，行数需要计算）

In [4]:
import numpy as np

arr=np.arange(16).reshape(2,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [5]:
arr.reshape(4,-1) #将arr变成4行的格式，列数自动计算的(c=4, d=16/4=4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
arr.reshape(8,-1) #将arr变成8行的格式，列数自动计算的(c=8, d=16/8=2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [7]:
arr.reshape(10,-1) #将arr变成10行的格式，列数自动计算的(c=10, d=16/10=1.6 != Int)

ValueError: cannot reshape array of size 16 into shape (10,newaxis)

numpy.arange(a,b,c)    从 数字a起, 步长为c, 到b结束，生成array
numpy.arange(a,b,c).reshape(m,n)  ：将array的维度变为m 行 n列。

In [8]:
import numpy as np
np.arange(1,12,2)#间隔2生成数组，范围在1到12之间

array([ 1,  3,  5,  7,  9, 11])

In [9]:
np.arange(1,12,2).reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

reshape(n,-1),将数组转换成 n 行：

In [11]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z.shape)
print(z.reshape(1,-1))

(4, 4)
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


reshape(2,-1)转换成两行：

In [12]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z.shape)
print(z.reshape(2,-1))

(4, 4)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


reshape(-1,n)，将数组转换成 n 列：

In [13]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z.shape)
print(z.reshape(-1,1))

(4, 4)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


reshape(-1,2)转化成两列

In [14]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z.shape)
print(z.reshape(-1,2))

(4, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


# mean
> numpy.mean() 函数，顾名思义就是计算平均值的，不过它可以沿指定轴计算算术平均值。    
> 返回数组元素的平均值。

In [15]:
import numpy as np
x = np.array([[1,2],[3,4]])
np.mean(x)

2.5

In [16]:
import numpy as np
x = 0.5 * 0.5
x = np.mean(x)
x

0.25